### ISSUE TITLE
readme의 url 비정상동작

### ISSUE THREAD

**Issue by AndersonChoi** [hatemogi/semver#1]
readme에 적힌 url이 정상적으로 열리지 않습니다.

> http://hatemogi.com/semver/

**Comment by hatemogi** [comment]
알려주셔서 감사합니다. 원문 사이트에 병합되기전 임시 페이지였고, 이후 병합이 완료되어 원문 사이트에 잘 보이고 있습니다. 임시 페이지 주소를 삭제하였습니다.
